stages:
  - lint
  - build
  - test
  - cleanup

Dockerfile lint:
  stage: lint
  image: hadolint/hadolint:latest-debian
  script:
    - hadolint Dockerfile

build:
  stage: build
  image: docker:stable
  script:
    - docker build --tag $CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA .

test:
  stage: test
  image: docker:stable
  script:
    - docker run --rm $CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA python3 -c 'from sys import version_info; print(version_info); assert version_info[0:2] == (3, 7)'

cleanup:
  stage: cleanup
  image: docker:stable
  script:
    - docker rmi $CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA
